version: 2.1

orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@1.2

workflows:
  test-dapp:
    jobs:
      - node/test:
          pkg-manager: yarn
          version: 14.17.4
      - heroku/deploy-via-git:
          force: true # this parameter instructs the push to use a force flag when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git
          app-name: deso-dapp
          requires:
            - node/run
          filters:
            branches:
              only: main
